version: '3.1'
services:
  app:
    container_name: springboot-gamehub
    image: springboot-gamehub
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1453
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gamehub